package panels;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author david
 */

import database.DatabaseManager;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.*;

public class MainWindow extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel mainPanel;

    public MainWindow(DatabaseManager dbm) {
   
        setTitle("Testprojekt V1");
        setSize(600, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
          
        // CardLayout för att hantera paneler
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);


        // Lägg till olika paneler
        mainPanel.add(new LoginPanel(this), "Login");
        mainPanel.add(new StartPanel(this), "StartPanel");
        mainPanel.add(new EmployeesPanel(this,dbm), "EmployeesPanel");
        mainPanel.add(new ProjectsPanel(this,dbm), "ProjectsPanel");
        // Lägg till huvudpanelen i fönstret
        add(mainPanel);

        // Visa Loginpanelen
         showPanel("Login");
    }

    public void showPanel(String panelName){
       cardLayout.show(mainPanel, panelName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
