package panels;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author david
 */

import database.DatabaseManager;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.*;
import models.*;

public class MainWindow extends javax.swing.JFrame {

    private JPanel mainPanel;
    private DatabaseManager dbm;
    public MainWindow(DatabaseManager dbm) {
  
        setTitle("Testprojekt V1");
        setSize(600, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dbm=dbm;
        mainPanel = new JPanel(new BorderLayout());
        add(mainPanel);
         showLoginPanel();
    }

    public void showLoginPanel(){
       showPanel(new LoginPanel(this));
    }
    public void showStartPanel(){
       showPanel(new StartPanel(this));
    }
    public void showEmployeesPanel(){
       showPanel(new EmployeesPanel(this,dbm));
    }
    public void showProjectsPanel(){
       showPanel(new ProjectsPanel(this,dbm));
    }
    public void showManageEmployeePanel(Employee employee){
       showPanel(new ManageEmployeePanel(this,dbm,employee));
    }

    private void showPanel(JPanel newPanel) {
        // Rensa mainPanel
        mainPanel.removeAll();

        // Lägg till den nya panelen
        mainPanel.add(newPanel, BorderLayout.CENTER);

        // Uppdatera layouten
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
